workspace(name = "bazel_android_sample_project")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

## rules_jvm_external

http_archive(
    name = "rules_jvm_external",
    strip_prefix = "rules_jvm_external-4.5",
    sha256 = "b17d7388feb9bfa7f2fa09031b32707df529f26c91ab9e5d909eb1676badd9a6",
    url = "https://github.com/bazelbuild/rules_jvm_external/archive/4.5.zip",
)
load("@rules_jvm_external//:defs.bzl", "maven_install")

maven_install(
    name = "maven",
    artifacts = [
        "junit:junit:4.13.2",
        "com.google.truth:truth:1.1.3",
        "org.jetbrains.kotlin:kotlin-stdlib-common:1.7.10",
        "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.10",
        "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.10",
        "org.jetbrains.kotlin:kotlin-stdlib:1.7.10",
        "org.robolectric:robolectric:4.10-alpha-1",
        "io.github.takahirom.roborazzi:roborazzi:1.2.0-alpha-1",
        "io.github.takahirom.roborazzi:roborazzi-painter:1.2.0-alpha-1",
        "io.github.takahirom.roborazzi:roborazzi-junit-rule:1.2.0-alpha-1",
        "androidx.test:monitor:1.6.1",
        "androidx.test:core:1.6.0-alpha01",
        "androidx.test.espresso:espresso-core:3.6.0-alpha01",
        "androidx.test:runner:1.6.0-alpha01",
        "androidx.test.ext:junit:1.2.0-alpha01",
        "androidx.test.services:storage:1.5.0-alpha01",
        "androidx.activity:activity-ktx:1.7.0",
        "androidx.activity:activity-compose:1.7.0",
        "androidx.compose.ui:ui:1.4.0",
        "androidx.lifecycle:lifecycle-runtime:2.6.1",
        "androidx.lifecycle:lifecycle-process:2.6.1",
        "androidx.activity:activity:1.7.0",
        "androidx.lifecycle:lifecycle-runtime-ktx:2.6.1",
        "androidx.core:core:1.9.0",
        "androidx.core:core-ktx:1.9.0",
        "androidx.compose.ui:ui-test:1.4.0",
        "androidx.compose.ui:ui-test-junit4:1.4.0",
        "com.dropbox.differ:differ:0.0.1"
    ],
    repositories = [
        "https://maven.google.com",
        "https://repo1.maven.org/maven2",
    ],
)

## Android

http_archive(
    name = "build_bazel_rules_android",
    sha256 = "cd06d15dd8bb59926e4d65f9003bfc20f9da4b2519985c27e190cddc8b7a7806",
    strip_prefix = "rules_android-0.1.1",
    urls = ["https://github.com/bazelbuild/rules_android/archive/v0.1.1.zip"],
)

load("@build_bazel_rules_android//android:rules.bzl", "android_sdk_repository")

android_sdk_repository(
    name = "androidsdk",
    api_level = 33,
)

## Kotlin

http_archive(
    name = "io_bazel_rules_kotlin",
    sha256 = "f033fa36f51073eae224f18428d9493966e67c27387728b6be2ebbdae43f140e",
    url = "https://github.com/bazelbuild/rules_kotlin/releases/download/v1.7.0-RC-3/rules_kotlin_release.tgz",
)

load("@io_bazel_rules_kotlin//kotlin:repositories.bzl", "kotlin_repositories")

kotlin_repositories()

load("@io_bazel_rules_kotlin//kotlin:core.bzl", "kt_register_toolchains")

kt_register_toolchains()

# Android Testing

http_archive(
    name = "robolectric",
    urls = ["https://github.com/robolectric/robolectric-bazel/archive/4.10.tar.gz"],
    strip_prefix = "robolectric-bazel-4.10",
    sha256 = "2929e39c81502e03628f1469d0f7fb411dd82d8c6d75244752bc2f6b537c5baa",
)
load("@robolectric//bazel:robolectric.bzl", "robolectric_repositories")

robolectric_repositories()


# Sky Lib

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_skylib",
    sha256 = "b8a1527901774180afc798aeb28c4634bdccf19c4d98e7bdd1ce79d1fe9aaad7",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/bazel-skylib/releases/download/1.4.1/bazel-skylib-1.4.1.tar.gz",
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.4.1/bazel-skylib-1.4.1.tar.gz",
    ],
)

load("@bazel_skylib//:workspace.bzl", "bazel_skylib_workspace")

bazel_skylib_workspace()
